services:
  multicontainer_app:
    image: esestephen/multicontainer_app:v0
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - 8501:8501

  db:
    image: postgres:17.7-bookworm
    restart: on-failure
    volumes:
    - postgres_data:/var/lib/postgresql/data
    postgres_data:
    environment:
    - POSTGRES_HOST: $(POSTGRES_HOST)
    - POSTGRES_USER: $(POSTGRES_USER)
    - POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
    - POSTGRES_DB: (POSTGRES_DB)
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-esestephen}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

